language: ruby
env:
  - RAILS_VERSION="5.0.0"
  - RAILS_VERSION="5.1.0"
  - RAILS_VERSION="5.2.0"

rvm:
  - 2.5.6
  - 2.6.3

# matrix:
#   exclude:
#     - env: RAILS_VERSION="4.0.0"
#       rvm: ruby-head
#     - env: RAILS_VERSION="4.1.0"
#       rvm: ruby-head
